name: release.yml
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - name: Run tests
        run: go test ./... -v -coverprofile=coverage.txt
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            binary: happcmd.exe
          - goos: linux
            goarch: amd64
            binary: happcmd-linux-amd64
          - goos: darwin
            goarch: amd64
            binary: happcmd-darwin-amd64
          - goos: darwin
            goarch: arm64
            binary: happcmd-darwin-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o ${{ matrix.binary }} .
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.binary }}